--1 
SELECT NOS FROM COMMANDE WHERE QUANTITE>10;

--2 
SELECT NOP,1.2*POIDS FROM PIECE;

--3 
SELECT COUNT(UNIQUE NOS)FROM COMMANDE;

--4
SELECT AVG(QUANTITE) FROM COMMANDE WHERE NOP=1;

--5 
SELECT * FROM PIECE WHERE NOP IN(
SELECT NOP FROM COMMANDE WHERE NOS=1);

--6
SELECT NOS  FROM COMMANDE C 
WHERE (SELECT SUM(QUANTITE) FROM COMMANDE WHERE NOS=C.NOS AND NOP=1)=
(SELECT SUM(QUANTITE) FROM COMMANDE WHERE NOS=C.NOS AND NOP=2)
;

--7
SELECT  UNIQUE NOS FROM COMMANDE C WHERE
(SELECT SUM(QUANTITE) FROM COMMANDE WHERE C.NOS=NOS AND C.NOP=2)>
(SELECT AVG(QUANTITE) FROM COMMANDE WHERE NOP=2);