/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp_last;
import java.io.*;
import java.net.SocketException;

public class Process extends Thread {
    public void run(){
        try{
            System.out.println("je suis dans le "+ Thread.currentThread().getName());
            Thread.sleep(3000);
            System.out.println("le" + Thread.currentThread().getName()+" est terminer");
        }
        catch(InterruptedException e){}
    }
        public static void main1(){
            System.out.println("creeer le thread 0");
            Thread T1 =new Process();
            System.out.println("creer Le Thread 1");
            Thread T2=new Process();
            T1.start();
            T2.start();

            }
}
