/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp3_2;

public class App {

    public static void main(String[] args) {

        MM1Simulation ms=new MM1Simulation(1,1);
        ms.simulate();
    }
}
