/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp2;

public class App {
    public static double multi1D(double[] A,double[]B){
        double sum =0;
        for(int i =0;i<=B.length-1;i++){
            sum+=A[i]*B[i];
        }
        return sum ;
    }
    public static double[][] multi(double[][] A, double[][] B){
        double [][] sol=new double[A.length][B[0].length];
        double sum;
        int b =B.length;
        double [] Bc=new double[b];
        for(int i =0;i<A.length;i++){
            for (int j = 0; j < B[i].length; j++) {
                sum=0;
                for (int j2 = 0; j2 < B.length; j2++) {
                    Bc[j2]=B[j2][j];
                } 
                    sol[i][j] =multi1D(A[i], Bc);
            }}

        return sol;

    }
    public static double[][] pow(double[][] A, int n){
        for (int i = 0; i < n; i++) {
            A=multi(A, A); 
        }
        return A;
    }
    public static void main(String[] args) {
        double [][] a ={{1,2},{1,1}};
        double [][] b ={{0.2,0.5}};

        // calculating
        double [][] sol=multi(b,a);

        // printing 
        for (int i = 0; i < sol.length; i++) {
          for (int j = 0; j < sol[0].length; j++) 
              System.out.print(sol[i][j]+" | "); 
          System.out.println();
        }

    }
}
