/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp2;

import java.util.Scanner;

public class App {
    public static double multi1D(double[] A,double[]B){
<<<<<<< HEAD
       double sum =0;
=======
        double sum =0;
>>>>>>> 6d7f5da10c9d50d0e8e488a267025386f53d8adb
        for(int i =0;i<=B.length-1;i++){
            sum+=A[i]*B[i];
        }
        return sum ;
    }
    public static double[][] multi(double[][] A, double[][] B){
        double [][] sol=new double[A.length][B[0].length];
        double sum;
        int b =B.length;
        double [] Bc=new double[b];
        for(int i =0;i<A.length;i++){
            for (int j = 0; j < B[i].length; j++) {
                sum=0;
                for (int j2 = 0; j2 < B.length; j2++) {
                    Bc[j2]=B[j2][j];
                } 
                    sol[i][j] =multi1D(A[i], Bc);
            }}

        return sol;
    }
    public static double[][] pow(double[][] A, int n){
        double[][] res=A;
        for (int i = 1; i < n; i++) {
            res=multi(A, res); 
        }
        return res;
    }
    public static void show(double[][] A){
        for (int i = 0; i < A.length; i++) {
          for (int j = 0; j < A[0].length; j++) {
              System.out.print(A[i][j]+" "); 
          } 
          System.out.println("|");
        }
    System.out.println();
    }
    public static double[][] pow(double[][] A, int n){
        for (int i = 0; i < n; i++) {
            A=multi(A, A); 
        }
        return A;
    }
    public static void main(String[] args) {
<<<<<<< HEAD
        double [][] a ={{0.8,0.2},{0.1,0.9}};
        double [][] b ={{0,0}};
        int n=0;
        Scanner keyboard =new Scanner(System.in);
        while(b[0][0]+b[0][1]!=1){
        System.out.println("donner X[0]:");
        b[0][0]=Double.valueOf(keyboard.nextLine());
        System.out.println("donner X[1]:");
        b[0][1]=Double.valueOf(keyboard.nextLine());
        if(b[0][0]+b[0][1]!=1)
            System.out.println("invalide matrix");
        }
        System.out.println("X0=");
       show(b);
       System.out.println("P=");
       show(a);
       System.out.println("donner n:"); 
    n=Integer.valueOf(keyboard.nextLine());
    show(multi(b,pow(a,n)));
        //show(a);
       // show(pow(a,1));
        //show(pow(a,2));
=======
        double [][] a ={{1,2},{1,1}};
        double [][] b ={{0.2,0.5}};

        // calculating
        double [][] sol=multi(b,a);

        // printing 
        for (int i = 0; i < sol.length; i++) {
          for (int j = 0; j < sol[0].length; j++) 
              System.out.print(sol[i][j]+" | "); 
          System.out.println();
        }

>>>>>>> 6d7f5da10c9d50d0e8e488a267025386f53d8adb
    }
}
