/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp2;

public class App {
    public static float multi1D(float[] A,float[]B){
        float sum =0;
        for(int i =0;i<=B.length-1;i++){
            sum+=A[i]*B[i];
            System.out.println("sum is "+sum);
        }
        return sum ;
    }
    public static float[][] multi(float[][] A, float[][] B){
        float [][] sol=new float[A.length][B[0].length];
        float sum;
        int b =B.length;
        float [] Bc=new float[b];
        for(int i =0;i<A.length;i++){
            for (int j = 0; j < B[i].length; j++) {
                sum=0;
                for (int j2 = 0; j2 < B.length; j2++) {
                    Bc[j2]=B[j2][j];
                }
                
                    sol[i][j] =multi1D(A[i], Bc);
                    System.out.println(sol[i][j]);
            }}

        return sol;

    }
    public static void main(String[] args) {
        float [][] a ={{1,2},{1,1}};
        float [][] b ={{1},{2}};
        System.out.println(a.length);
        System.out.println(multi(a, b));
    }
}
