/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp3;

import java.lang.*;
import java.lang.Math;
public class App {

    private static double lambda=0.5;
    private static double miu=1.;

    private static  Boolean busy;

    public static void main(String[] args) {
        Server server = new Server();
        for (int i=0;i<60 ;i++ ) {
            new Thread(()->{
                Client c=new Client(1,-Math.log(Math.random())/lambda,-Math.log(Math.random())/miu);
                try {
                    Thread.sleep((int)(c.tempsArrivee*1000));   
                } catch(Exception e){
                    e.printStackTrace();
                }
                server.serve(c);
            }).start();
        }
    }
}
