/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp12;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        Client client=new Client(4446);
        client.send("ay letd","127.0.0.1",4445);
    }
}
