/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TP1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(args[0]);
        System.out.println(new App().getGreeting());
        System.out.println("1");
        if(args[0].equals("c"))
            try {

                Client client=new Client("126.0.0.1",4445);
                System.out.println("starting the client");
                client.run();
            } catch (Exception e) {
                //TODO: handle exception
            }
        System.out.println("2"); 
        if(args[0].equals("s")){

            Server server= new Server();
            System.out.println("starting the server");
            server.run();}
    }
}
